qiwi = 'eyJ2ZXJzaW9uIjoiUDJQIiwiZGF0YSI6eyJwYXlpbl9tZXJjaGFudF9zaXRlX3VpZCI6Ijh2ZGt4Yy0wMCIsInVzZXJfaWQiOiI3OTUwMDQ5MDQwOSIsInNlY3JldCI6ImJlNGQ4ZjM0YjJjYzM1YTMzYzViYjljY2FkNjA3ZGU5M2VkMzk2MWFiZDBjOTg0NGNlOTJjYWY3ZWI5YzZmYzcifX0='
dadata = 'a2ef57bedfa524e0091f9e840c4925b79f90afd0'
city = 'uhfeerii'
token = 'vk1.a.7D5ocSiAevhf6aYViIBPA2gnupW0cUc3Is3NR-4tg4wFLSiW0Y9vcbgFllaIfNByLhvf-FPveZ2FH7jeKsQHeXvxdqIX762gpAJPiwvjMhXOF4YswZSoE07Glj3wY5ANn7KG-vavppcQ54FLjisarSxstjm_phyPThYQcv6RZnra85FF9eo-edAomPpGAyBcL70V5S4B3hH4KkOpTD1LdA'
