from vkbottle import Keyboard, KeyboardButtonColor, Text, EMPTY_KEYBOARD, VKPay

class keyboards:
	EMPTY = EMPTY_KEYBOARD
	class inline:
		delivery_driver = lambda x: (Keyboard(one_time = False, inline = True)
			.add(Text('Принять доставку &#128526;', payload = {'driver': 0, 'delivery': 1, 'other': x}), color = KeyboardButtonColor.POSITIVE)
		).get_json()
		driver_new_order = lambda x: (Keyboard(one_time = False, inline = True)
			.add(Text('Принять заявку &#128526;', payload = {'driver': 1, 'order': 1, 'other': x}), color = KeyboardButtonColor.POSITIVE)
		).get_json()
		qiwi_check_pay = lambda x: (Keyboard(one_time = False, inline = True)
			.add(Text('Проверить оплату', payload = {'driver': 0, 'qiwi': 0, 'other': x}), color = KeyboardButtonColor.PRIMARY)
		).get_json()

	driver_registartion_success = (Keyboard(one_time = True, inline = False)
			.add(Text('Моя анкета &#128526;', payload = {'driver': 0, 'profie': 0}), color = KeyboardButtonColor.POSITIVE)
		).get_json()
	start = (Keyboard(one_time = True)
		.add(Text('Я пассажир &#128519;', payload = {'passanger': 1}), color = KeyboardButtonColor.POSITIVE)
		.row()
		.add(Text('Я водитель &#128526;', payload = {'driver': 1}), color = KeyboardButtonColor.POSITIVE)
	).get_json()
	passanger_get_taxi = (Keyboard(one_time = False)
		.add(Text('Отменить вызов', payload = {'user': 0, 'cancel': 0}), color = KeyboardButtonColor.NEGATIVE)
		.row()
		.add(Text('Успешно доехал', payload = {'user': 0, 'success': 0}), color = KeyboardButtonColor.POSITIVE)
	).get_json()
	choose_service = (Keyboard(one_time = False)
		.add(Text('Заказать такси &#128662;', payload = {'taxi': 0}), color = KeyboardButtonColor.PRIMARY)
		.row()
		.add(Text('Заказать доставку &#128640;', payload = {'delivery': 0}), color = KeyboardButtonColor.POSITIVE)
		.row()
		.add(Text('Моя анкета &#128519;', payload = {'user': 0, 'profile': 0}), color = KeyboardButtonColor.SECONDARY)
	).get_json()
	user_profile = (Keyboard(one_time = False)
		.add(Text('Редактировать анкету', payload = {'user': 0, 'edit': 0}), color = KeyboardButtonColor.POSITIVE)
		.row()
		.add(Text('Удалить анкету', payload = {'user': 0, 'delete': 0}), color = KeyboardButtonColor.NEGATIVE)
		.row()
		.add(Text('Назад', payload = {'user': 0, 'back': 0}), color = KeyboardButtonColor.PRIMARY)
	).get_json()
	driver_profile = (Keyboard(one_time = False)
		.add(Text('Пополнить при помощи VK PAY', payload = {'driver': 0, 'money': 'vk pay'}), color = KeyboardButtonColor.POSITIVE)
		.add(Text('Пополнить при помощи QIWI', payload = {'driver': 0, 'money': 'qiwi'}), color = KeyboardButtonColor.POSITIVE)
		.row()
		.add(Text('Удалить анкету', payload = {'driver': 0, 'delete': 0}), color = KeyboardButtonColor.NEGATIVE)
		.row()
		.add(Text('Редактировать анкету', payload = {'driver': 0, 'edit': 0}), color = KeyboardButtonColor.PRIMARY)
	).get_json()
	user_cancel = (Keyboard(one_time = False)
		.add(Text('Назад', payload = {'cancel': 1}), color = KeyboardButtonColor.NEGATIVE)
	).get_json()
	user_cancel_order = (Keyboard(one_time = False)
		.add(Text('Вызвать повторно', payload = {'user': 0, 'return': 0}), color = KeyboardButtonColor.POSITIVE)
		.row()
		.add(Text('Отменить вызов', payload = {'user': 0, 'cancel': 0}), color = KeyboardButtonColor.NEGATIVE)
	).get_json()
	driver_order_complete = lambda link: (Keyboard(one_time = False) 
		.add(Text('Заказ выполнен &#128526;', payload = {'driver': 0, 'success': 0, 'other': link}), color = KeyboardButtonColor.POSITIVE)
		.row()
		.add(Text('Отказаться от заказа', payload = {'driver': 0, 'cancel': 0, 'other': link}), color = KeyboardButtonColor.NEGATIVE)
	).get_json()
	vk_pay_keyboard = lambda group_id, amount: (Keyboard(one_time = True)
		.add(VKPay(hash = f'action=pay-to-group&amount={amount}&group_id={group_id}'))
	)
	starter = Keyboard(one_time = True).add(Text('Начать'), color = KeyboardButtonColor.PRIMARY).get_json()